bdd_demo/lib/bdd_demo_web/router.ex
defmodule BddDemoWeb.Router do
  use BddDemoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BddDemoWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/sign_up", SignUpController, only: [:new, :create]
  end

  # Other scopes may use custom stacks.
  # scope "/api", BddDemoWeb do
  #   pipe_through :api
  # end
end

bdd_demo/lib/bdd_demo/accounts/accounts.ex
defmodule BddDemo.Accounts do
  @moduledoc """
  The Accounts context.
  """

  import Ecto.Query, warn: false
  alias BddDemo.Repo

  alias BddDemo.Accounts.User

  @doc """
  Returns the list of users.

  ## Examples

      iex> list_users()
      [%User{}, ...]

  """
  def list_users do
    Repo.all(User)
  end

  @doc """
  Gets a single user.

  Raises `Ecto.NoResultsError` if the User does not exist.

  ## Examples

      iex> get_user!(123)
      %User{}

      iex> get_user!(456)
      ** (Ecto.NoResultsError)

  """
  def get_user!(id), do: Repo.get!(User, id)

  @doc """
  Sign up a new.

  ## Examples
      iex> signup_user(%{username: "newuser", password: "password", password_confirmation: "password"})
      {:ok, %User{}}

      iex> signup_user(%{username: "newuser"})
      {:error, %Ecto.Changeset{}}
  """
  def signup_user(%{} = attrs) do
    %User{}
    |> User.signup_changeset(attrs)
    |> Repo.insert
  end

  @doc """
  Creates a user.

  ## Examples

      iex> create_user(%{field: value})
      {:ok, %User{}}

      iex> create_user(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_user(attrs \\ %{}) do
    %User{}
    |> User.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a user.

  ## Examples

      iex> update_user(user, %{field: new_value})
      {:ok, %User{}}

      iex> update_user(user, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_user(%User{} = user, attrs) do
    user
    |> User.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a User.

  ## Examples

      iex> delete_user(user)
      {:ok, %User{}}

      iex> delete_user(user)
      {:error, %Ecto.Changeset{}}

  """
  def delete_user(%User{} = user) do
    Repo.delete(user)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking user changes.

  ## Examples

      iex> change_user(user)
      %Ecto.Changeset{source: %User{}}

  """
  def change_user(%User{} = user) do
    User.changeset(user, %{})
  end
end

bdd_demo/lib/bdd_demo/accounts/user.ex
defmodule BddDemo.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset


  schema "users" do
    field :password, :string
    field :username, :string

    field :password_confirmation, :string, virtual: true

    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:username, :password])
    |> validate_required([:username, :password])
  end

  @doc false
  def signup_changeset(user, attrs) do
    user
    |> cast(attrs, [:username, :password, :password_confirmation])
    |> validate_required(:username, message: "请填写用户名")
    |> validate_required([:password, :password_confirmation])
    |> validate_length(:username, min: 8, message: "用户名不能少于8个字符")
    |> validate_confirmation(:password, message: "密码不一致")
  end
end

bdd_demo/lib/bdd_demo/application.ex
defmodule BddDemo.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(BddDemo.Repo, []),
      # Start the endpoint when the application starts
      supervisor(BddDemoWeb.Endpoint, []),
      # Start your own worker by calling: BddDemo.Worker.start_link(arg1, arg2, arg3)
      # worker(BddDemo.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: BddDemo.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    BddDemoWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

bdd_demo/lib/bdd_demo/repo.ex
defmodule BddDemo.Repo do
  use Ecto.Repo, otp_app: :bdd_demo

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

bdd_demo/lib/bdd_demo_web/controllers/page_controller.ex
defmodule BddDemoWeb.PageController do
  use BddDemoWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

bdd_demo/lib/bdd_demo_web/controllers/sign_up_controller.ex
defmodule BddDemoWeb.SignUpController do
  use BddDemoWeb, :controller

  alias BddDemo.Accounts
  alias BddDemo.Accounts.User

  def new(conn, _params) do
    changeset = Accounts.change_user(%User{})
    render conn, "new.html", changeset: changeset
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.signup_user(user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "Welcome #{user.username}")
        |> redirect(to: page_path(conn, :index))
      {:error, changeset} ->
        conn
        |> render("new.html", changeset: changeset)
    end

  end

end

bdd_demo/lib/bdd_demo_web/views/error_view.ex
defmodule BddDemoWeb.ErrorView do
  use BddDemoWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

bdd_demo/lib/bdd_demo_web/views/layout_view.ex
defmodule BddDemoWeb.LayoutView do
  use BddDemoWeb, :view
end

bdd_demo/lib/bdd_demo_web/views/page_view.ex
defmodule BddDemoWeb.PageView do
  use BddDemoWeb, :view
end

bdd_demo/lib/bdd_demo_web/views/sign_up_view.ex
defmodule BddDemoWeb.SignUpView do
  use BddDemoWeb, :view
end

bdd_demo/lib/bdd_demo_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello BddDemo!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

bdd_demo/lib/bdd_demo_web/templates/page/index.html.eex
<div class="jumbotron" id="current_page" page_id="home_page">
  <h2><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
  <p>
    <a href="<%= sign_up_path(@conn, :new) %>" id="btn_sign_up">注册新账号</a>
  </p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

bdd_demo/lib/bdd_demo_web/templates/sign_up/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <div class="form-group">
    <%= label f, :username, class: "control-label" %>
    <%= text_input f, :username, class: "form-control", id: "username_field" %>
    <%= error_tag f, :username %>
  </div>
  <div class="form-group">
    <%= label f, :password, class: "control-label" %>
    <%= text_input f, :password, class: "form-control", id: "password_field" %>
    <%= error_tag f, :password %>
  </div>
  <div class="form-group">
    <%= label f, :password_confirmation, class: "control-label" %>
    <%= text_input f, :password_confirmation, class: "form-control", id: "password_confirmation_field" %>
    <%= error_tag f, :password_confirmation %>
  </div>
  <div class="form-group">
    <%= submit "Sign Up", class: "btn btn-primary", id: "btn_sign_up" %>
  </div>
<% end %>

bdd_demo/lib/bdd_demo_web/templates/sign_up/new.html.eex
<div id="current_page" page_id="sign_up_page">
  <h1>新用户注册</h1>
  <p>
    <%= render "form.html", Map.put(assigns, :action, sign_up_path(@conn, :create)) %>
  </p>
</div>